# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='chosen_robot_key',
        ),
        migrations.AddField(
            model_name='player',
            name='chosen_robot',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bots.Robot'),
        ),
    ]
