# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-27 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0003_auto_20180227_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='value',
            field=models.IntegerField(),
        ),
    ]
