# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-28 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0004_auto_20180227_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='robot',
            name='accuracy',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='armour',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='dodge',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='robot',
            name='weapon',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
