# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 20:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0005_auto_20180228_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('challengee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challengee', to='bots.Player')),
                ('challenger', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='bots.Player')),
                ('robots', models.ManyToManyField(to='bots.Robot')),
            ],
        ),
    ]
