# -*- coding: utf-8 -*-
# Generated by Django 1.9.10 on 2018-03-15 20:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0006_challenge'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_bots', models.IntegerField(default=1)),
                ('bots', models.ManyToManyField(to='bots.Robot')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='robots',
        ),
        migrations.AddField(
            model_name='challenge',
            name='num_bots',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challengee',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challengee', to='bots.Team'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenger',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='bots.Team'),
        ),
    ]
