# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bots', '0007_auto_20180315_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='robot',
            name='accuracy',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='armour',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='dodge',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='speed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='robot',
            name='weapon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
